#!/usr/bin/env bash
# bash script that Install nginx web server

#update the server
sudo apt update
# installl nginx
sudo apt-get install nginx -y
# change ownership
sudo chown -R "$USER":"$USER" /var/www
# update the default file dispayed
echo "Hello World!" | tee /
sudo systemctl restart nginx
sudo apt autoremove -yvar/www/html/index.nginx-debian.html
# restart nginx