#!/usr/bin/env bash
# Install nginx web server

#!/usr/bin/env bash
# bash script that Install nginx web server

#update the server
sudo apt update
sudo apt-get install nginx -y
sudo chown -R "$USER":"$USER" /var/www
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sudo systemctl restart nginx
sudo apt autoremove -y